### PR TITLE
[PR] `Flutter` + `Phoenix` `Channels` Demo Initial Implementation.  

### LINKED ISSUE #1: Why? What? Who? How?
We are building our backend in `Phoenix` as outlined in: https://github.com/dwyl/technology-stack#phoenix
We need to showcase how to interact with `Phoenix` from `Flutter` in the _simplest_ way possible. 

Currently `phoenix_socket`: https://pub.dev/packages/phoenix_socket 
image

Appears to be the best `<option>`. 💭 

Although the slow response rate on the open PRs: https://github.com/braverhealth/phoenix-socket-dart/pulls

image

Is less than reassuring... ⏳ 
e.g: https://github.com/braverhealth/phoenix-socket-dart/pull/55 should at least have a _comment_ by now ... 🤷‍♂️ 

`if` you find a _better_ one, please share. 🙏 
If you get stuck, take a look at: https://github.com/supabase/supabase-flutter#realtime-data-as-stream
Disect their code and if needed (comment first) build our own library to do this!

# Todo ✅ 

+ [x] Document _every_ step you take along the way in building this. 📝 
  it needs to be followed by someone whose time is _very_ scarce so [please don't skip any steps](https://github.com/dwyl/learn-flutter/issues/75) ... 🙏 
+ [x] Launch a basic `Phoenix` App that has a `channel`.
  + [x] A good _pre_-task would be to `UPDATE` our existing `phoenix-chat-example`. 
  please see: https://github.com/dwyl/phoenix-chat-example/issues/149
  and use that as the basis for this integration.
+ [x] Create a basic `Flutter` app 
   + [x] add `phoenix_socket` as a dependency.
+ [x] Run both on `localhost` and attempt to connect `Flutter` to `Phoenix`.
+ [x] Show "who is online" in the `Phoenix` App.
+ [x] Display this data in the `Flutter` App.
+ [x] **Bonus Level**: deploy the `Flutter` app to `Fly.io` as a `PWA` see: https://github.com/dwyl/learn-flutter/issues/9
  + [ ] Connect the deployed `Flutter` app to https://phoenix-chat.fly.dev to showcase the "Production" version. 🚀 

That's it. 

This should take a couple of days to document & build with tests in both `Phoenix` and `Flutter`.

Please leave a comment on this issue with ***`each`*** step you take in your quest. 
The resulting repo/demo should be easy for _anyone_ to run.
If you have _any_ questions, please comment. 
And if I take longer than **`T1h`** to respond on `GitHub` signal-message me with a direct link to the issue comment. 
e.g: https://github.com/dwyl/learn-flutter/issues/9#issuecomment-1413898764

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #1 

This PR will create a `Flutter` application that will connect to a `Phoenix` server through websockets
stating who is online or not.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Still on the fence about using https://github.com/dwyl/phoenix-chat-example/pull/152 or just creating my own `Phoenix` server that only has presence to check who is online or not... 

Will focus on creating the Flutter app first, try to connect to a simple channel on a locally-developed Phoenix and then tackle this.

**Comment by LuchoTurtle** [comment]
Will be having both `Phoenix` and `Flutter` in their own respective folders in this repo. 
I found the `Phoenix` server in https://github.com/dwyl/phoenix-chat-example/pull/152 much more complex than it needs to be for this demo (e.g. we don't need a database for this repo).

I'm going to create a simple `Phoenix` server here and develop both `Flutter` and `Phoenix` along the way. Each folder has instructions on how to get both up and running. The main `README` of this repo makes reference to both of them and clarifies that you need different terminal/VSCode windows if you want to give this project a whirl.

**Comment by LuchoTurtle** [comment]
I finally got Flutter and Phoenix to connect. It wasn't working initially because the Phoenix Socket URL wasn't quite clear which one I had to connect to.

Turns out
`ws://localhost:4000/socket/websocket` is the correct one. The topic **has to be specified** or else it errors out.

I've added Presence and I'm trying to "catch" user disconnects to properly show the list of connected users on the Flutter counterpart. I've tried using Hoppscotch for this but I can't seem to send parameters (user information) through here (at least successfully). 

image
image

Trying to get two emulators working so I can check multiple clients and see the `presence_diff` on both joining and leaving scenarios...

**Comment by LuchoTurtle** [comment]
Finally got it working. 

image

At first I was a bit confused with how `presence_diff` from [Presence](https://hexdocs.pm/phoenix/Phoenix.Presence.html) was actually going to be captured in Flutter. With LiveView, this was trivial:

> Finally, a diff of presence join and leave events will be sent to the client as they happen in real-time with the "presence_diff" event. The diff structure will be a map of :joins and :leaves of the form.

I *had* to use `presence_diff` so I knew which processes were connected to the Phoenix Server (after, obviously, setting up Presence and tracking users after joining the channel).

However, I couldn't get this to work with Flutter. I tried capturing the events normally in the channel (like `pinging` or `shouting` (broadcast)) from Elixir to Flutter but Flutter wasn't capturing anything.

Turns out that tI needed to use `PhoenixPresence(channel)` object and specify the channel and use the `onSync` callback to capture both `presence_state` and `presence_diff`.

From there on out, I could parse and map the meta information in each.

All of these steps will be detailed in the `README` file, just wanted to give an update on the matter.

**Comment by nelsonic** [comment]
@LuchoTurtle looking good. thanks for capturing as much of your learning as possible. 👍

**Comment by LuchoTurtle** [comment]
Successfully deployed Flutter and Phoenix on Fly.io (firstly testing on personal account).

Therefore, the `fly.toml` file inside the `app` folder is already created and can be deployed with `fly launch` and just by following the instructions. This should address https://github.com/dwyl/learn-flutter/issues/9


However, I'm having trouble connecting to the WebSockets of the deployed Phoenix server.
I've tried using `Hoppscotch` (which was previously working when I was running the server on `localhost`) but I can't seem to do so whilst it is deployed in Fly.io.

image

**Comment by LuchoTurtle** [comment]
I cannot for the life of me connect from a deployed Flutter app to a deployed Phoenix app.
I'm constantly testing new URLs on my personal Fly.io pages.

https://flutter-phoenix-channels-backend.fly.dev/
https://flutter-phoenix-channels-frontend.fly.dev/


But I keep getting an error trying to connect to the Phoenix websocket.
At first I thought it was because I didn't define a `:host` when releasing the production bundle of the Phoenix Server.
I've changed it to the following:

```elixir
config :app, AppWeb.Endpoint,
 cache_static_manifest: "priv/static/cache_manifest.json",
 url: [host: "flutter-phoenix-channels-backend.fly.dev"],   # must be the same as in `fly.toml` file - PHX_HOST variable
 check_origin: false
```

> **Note** I know that `check_origin` should have the URL of the frontend. I'm turning it off to just try and connect to the server from anywhere.

I've inclusively tried to connect to a`wss` socket, instead of just `ws`, because Flutter was complaining it wasn't secure.
Phoenix does support `wss` -> https://elixirforum.com/t/security-https-wss-pfs-and-e2ee-with-phoenix-framework/2091/4

Even after this change, I can't seem to connect...

image

**Comment by LuchoTurtle** [comment]
image

Was testing different settings but it seems that Fly.io is having trouble with deployments :/

**Comment by LuchoTurtle** [comment]
It's down now 
image

:/

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for pair-debugging this with me so I could understand how it works. 👌 
Looking good: https://flutter-phoenix-channels-frontend.fly.dev/#/
image

**Comment by LuchoTurtle** [comment]
I think it looks good for review. 
This also addresses https://github.com/dwyl/learn-flutter/issues/9#issuecomment-1414006793.

**Comment by nelsonic** [comment]
The [`README.md`](https://github.com/dwyl/flutter-phoenix-channels-demo/tree/a6a2951b944c758dca8e25b4a54eadd9efe02555) doesn't contain the instructions required to actually _run_ the finished demo. 🤷‍♂️ 
image

It just goes straight into _Creating_ the App. 
Also, I don't understand why you don't have a basic homepage in the `Phoenix` App ... 🤷‍♂️ 

image

What is the _advantage_ to having a `404` when the person opens http://localhost:4000/ in a browser? 🤷‍♂️ 
I can't say I understand this decision.

**Comment by nelsonic** [comment]
This GIF is microscopic:
image

Why? 🤷‍♂️

**Comment by LuchoTurtle** [comment]
In the section, I state that each folder (which have links to their `readme`s) has instructions on how to run each component, inclusively saying that each one should be run on a different terminal.

The `Phoenix` server only serves web sockets, it's not meant for the person to access it in the browser. They just need to fire up the server in the terminal, as suggested in the README. The Phoenix server was created without any HTML, mailer, swoosh or Ecto (as described in the instructions) to keep the code as simple as possible and focus solely on the web sockets component.

And I personally don't find the gif microscopic (?), I actually made it have these dimensions *intentionally* so they wouldn't take the whole width needlessly.

**Comment by nelsonic** [comment]
Nope. 
The _first_ thing I did was open two terminal windows:
image

There are no instructions there. 
There's no mention of having to open the **two _separate_ `README.md` files**. 
"_follow the instructions inside each one_" is not instructing me to open a `README.md` file _contained_ within the directories. It's making an _assumption_ that I will "figure out" where these instructions are ... we don't like _assumptions_.

**Comment by LuchoTurtle** [comment]
I thought adding "follow the instructions inside each one" would grammatically make sense after saying "folders". But if it's not clear to you, it's no bueno. 
Assign the PR back to me and I'll re-write it 👍

**Comment by nelsonic** [comment]
Why are you using an iPhone 14 Pro ***MAX*** as your simulator device?
image

Are you _deliberately_ trying to make your screenshots as big as they possibly can be? 🤷‍♂️ 

The content you are showing in the App is _tiny_:
image

Why not pick a device that doesn't fill my screen with more than 50% of whitespace? 
You know ... something like the `iPhone 13 Mini` that is _far_ more accessible and uses _considerably_ less screen real-estate:

image

Yes, it's an "inferior" device. But as noted in: 
https://www.figma.com/file/WrpkKGJNYZbeCzMRDVtvQLbC/dwyl-app?node-id=1477%3A3375
We want to _focus_ on the smaller device and then make sure that all our UI/UX "scales" to the bigger devices.

**Review by nelsonic — APPROVED** [review]
This demo could _definitely_ have been a lot simpler by connecting the `Flutter` app to the `Chat Example`: https://phoenix-chat.fly.dev/ which has `Phoenix Channels`. 
So this demo _only_ needed to focus on the `Flutter` part and not force them to understand how the `Phoenix` part works. Not that we don't _want_ people to understand both parts. But  if we can _simplify_ it for people learning that's a _good_ thing. 

Anyway, merging. It's fine. 👌

**Pull request merged**
